### ISSUE TITLE
Web version broken when updating wasm-bindgen to 0.2.85

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#14265]
```

  1) [chromium-desktop] › on-chain-state-mgmt-zkapp-ui.spec.ts:4:3 › On-Chain State Management zkApp UI › should load page and initialize SnarkyJS 

    Error: expect(received).toContainText(expected)

    Expected string: "SnarkyJS initialized after"
    Received string: "No data available yet."
    Call log:
```

See https://github.com/o1-labs/o1js/pull/1160, while fixing https://github.com/MinaProtocol/mina/issues/14253

**Comment by dannywillems** [comment]
There is also https://github.com/rustwasm/wasm-bindgen/commit/46ea32f20eb4e56ac35ef46acc438d7f4767c12c

**Comment by dannywillems** [comment]
While running locally, getting in the console:
```
index.js:11398 Uncaught ReferenceError: init is not defined
    at plonkWasm (index.js:11398:14)
    at index.js:13812:12
```

**Comment by dannywillems** [comment]
Also this: https://github.com/rustwasm/wasm-bindgen/commit/76e4cad8bb0dadc27b532bc051817ecf9bc3ac7a

**Comment by dannywillems** [comment]
We must change:
- `getImports` into `__wbg_get_imports`
- `finalizeInit` into `__wbg_finalize_init`
- `init` into `__wbg_init`
- `load` into `__wbg_load`
- `initMemory` into `__wbg_init_memory`

**Comment by joseandro** [comment]
@nicc and @garwalsh is it OK to assign this task to your team?

**Comment by MartinMinkov** [comment]
I believe these PRs will fix this issue. @dannywillems already did the heavy lifting it seems like, just a few spots needed updating :D 

o1js: https://github.com/o1-labs/o1js/pull/1164
Bindings: https://github.com/o1-labs/o1js-bindings/pull/173
