### ISSUE TITLE
Genesis directory grows in size on Testworld

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#14548]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

There are many comments on Discord with the node crashing due to being out of disk space. As one example, this user had a genesis dir exceeding 400GB

![image](https://github.com/MinaProtocol/mina/assets/135382/370c3284-fd8e-431f-9131-c8d5e3c8e58e)

### Steps to Reproduce

See Discord comments

### Expected Result

Genesis dir not to grow unbounded

### Actual Result

Genesis dir can grow to fill entire disk

### How frequently do you see this issue?

Sometimes

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
Latest Testworld
```

**Comment by deepthiskumar** [comment]
Could you please list the contents of `./.mina-config/genesis` (`ls -la  ./.mina-config/genesis/*` equivalent)?

**Comment by CertHum-Jim** [comment]
> Could you please list the contents of `./.mina-config/genesis` (`ls -la ./.mina-config/genesis/*` equivalent)?

We encountered this problem over the weekend. It's a lot of output and I've put what was requested in pastebin. It appeared at the time that this was actually an effect of what of some prior problems. The timeline it seems was:

1) Node loses synch 2) Node goes into into restart cycle where it crashes because a) couldn't connect to any seed nodes on Berkely seed list, or b)concurrent map write crash.

I've put snippits of the two crash loops below, and can provide more info as requested.

https://pastebin.com/7AC01XKq

```[2023-11-11 01:18:16]  Nov 11 06:10:12 --- mina[1099911]: {"timestamp":"2023-11-11 06:10:12.553000Z","level":"Error","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"libp2p_helper: failed to connect to peer: {12D3KooWAdgYL6hv18M3iDBdaK1dRygPivSfAfBNDzie6YqydVbs: [/dns4/seed-1.berkeley.o1test.net/tcp/10000]}failed to dial 12D3KooWAdgYL6hv18M3iDBdaK1dRygPivSfAfBNDzie6YqydVbs:\n  * [/ip4/34.170.114.52/tcp/10000] dial backoff","metadata":{"caller":"libp2p_helper/config_msg.go:43"}}
[2023-11-11 01:18:16]  Nov 11 06:10:12 --- mina[1099911]: {"timestamp":"2023-11-11 06:10:12.554000Z","level":"Error","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"libp2p_helper: failed to connect to peer: {12D3KooWLjs54xHzVmMmGYb7W5RVibqbwD1co7M2ZMfPgPm7iAag: [/dns4/seed-2.berkeley.o1test.net/tcp/10001]}failed to dial 12D3KooWLjs54xHzVmMmGYb7W5RVibqbwD1co7M2ZMfPgPm7iAag:\n  * [/ip4/35.192.28.217/tcp/10001] dial backoff","metadata":{"caller":"libp2p_helper/config_msg.go:43"}}
[2023-11-11 01:18:16]  Nov 11 06:10:12 --- mina[1099911]: {"timestamp":"2023-11-11 06:10:12.554000Z","level":"Error","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"libp2p_helper: failed to connect to peer: {12D3KooWEiGVAFC7curXWXiGZyMWnZK9h8BKr88U8D5PKV3dXciv: [/dns4/seed-3.berkeley.o1test.net/tcp/10002]}failed to dial 12D3KooWEiGVAFC7curXWXiGZyMWnZK9h8BKr88U8D5PKV3dXciv:\n  * [/ip4/34.135.63.47/tcp/10002] dial backoff","metadata":{"caller":"libp2p_helper/config_msg.go:43"}}
[2023-11-11 01:18:16]  Nov 11 06:10:12 --- mina[1099911]: {"timestamp":"2023-11-11 06:10:12.555000Z","level":"Error","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"libp2p_helper: failed to connect to peer: {12D3KooWM33uyKhTejdvrM6bJdu72jvjbTiiZTW3kU4SHS3SMuGq: [/dns4/seed-0-production-berkeley.minaprotocol.network/tcp/10001]}failed to dial 12D3KooWM33uyKhTejdvrM6bJdu72jvjbTiiZTW3kU4SHS3SMuGq:\n  * [/ip4/35.81.90.156/tcp/10001] dial backoff\n  * [/ip4/50.112.230.227/tcp/10001] dial backoff\n  * [/ip4/100.20.193.204/tcp/10001] dial backoff","metadata":{"caller":"libp2p_helper/config_msg.go:43"}}
[2023-11-11 01:18:16]  Nov 11 06:10:12 --- mina[1099911]: {"timestamp":"2023-11-11 06:10:12.656000Z","level":"Error","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"libp2p_helper: failed to routing advertise: failed to find any peer in table","metadata":{"caller":"libp2p_helper/config_msg.go:112"}}
[2023-11-11 01:18:16]  Nov 11 06:10:12 --- mina[1099911]: {"timestamp":"2023-11-11 06:10:12.656533Z","level":"Warn","source":{"module":"Gossip_net__Libp2p","location":"File \"src/lib/gossip_net/libp2p.ml\", line 520, characters 23-49"},"message":"starting libp2p up failed: $error","metadata":{"error":{"commit_id":"4061884b18137c1182c7fcfa80f52804008a2509","string":"libp2p error: failed to find any peer in table"},"host":"57.128.141.207","peer_id":"12D3KooWMngwxvqxbVTufQc1bNnGs2dgrarkVyw4RoteAKL2LTGz","port":8302}}
[2023-11-11 01:18:16]  Nov 11 06:11:07 --- mina[1099911]: {"timestamp":"2023-11-11 06:11:07.508633Z","level":"Error","source":{"module":"Transition_router","location":"File \"src/lib/transition_router/transition_router.ml\", line 319, characters 12-24"},"message":"Failed to find any peers during initialization (crashing because this is not a seed node)","metadata":{"host":"57.128.141.207","peer_id":"12D3KooWMngwxvqxbVTufQc1bNnGs2dgrarkVyw4RoteAKL2LTGz","port":8302}}
[2023-11-11 01:18:16]  Nov 11 06:11:07 --- systemd[389119]: mina.service: Main process exited, code=exited, status=1/FAILURE
[2023-11-11 01:18:16]  Nov 11 06:11:07 --- systemd[389119]: mina.service: Failed with result 'exit-code'.
[2023-11-11 01:18:16]  Nov 11 06:11:07 --- systemd[389119]: mina.service: Consumed 6min 4.516s CPU time.
[2023-11-11 01:18:16]  Nov 11 06:11:37 --- systemd[389119]: mina.service: Scheduled restart job, restart counter is at 2.
[2023-11-11 01:18:16]  Nov 11 06:11:37 --- systemd[389119]: Stopped Mina Daemon Service.
[2023-11-11 01:18:16]  Nov 11 06:11:37 --- systemd[389119]: mina.service: Consumed 6min 4.516s CPU time.```

and the concurrent map write issues seen before the last upgrade.

```[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: fatal error: concurrent map writes
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: goroutine 454 [running]:
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: main.AddPeerReq.handle({0xc0032a82a0, 0x50, {0x8, 0x1}, 0x3d, 0x0}, 0xc0001d6ea0, 0x0?)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /workdir/src/app/libp2p_helper/src/libp2p_helper/peer_msg.go:44 +0x278
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: main.(*app).handleIncomingMsg.func1(0xc0032a82a0?, 0x800000008?)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /workdir/src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go:67 +0x2dd
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: main.(*app).handleIncomingMsg(0xc0001d6ea0, 0xc003296210)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /workdir/src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go:68 +0x9d
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: created by main.main
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /workdir/src/app/libp2p_helper/src/libp2p_helper/main.go:191 +0x807
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: goroutine 1 [syscall]:
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: syscall.Syscall(0x0?, 0xc0032a84e0?, 0x800000?, 0x7ffff800000?)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/syscall/syscall_linux.go:68 +0x27
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: syscall.read(0xc0000560c0?, {0xc0000fc110?, 0x0?, 0xc00073fcf0?})
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:696 +0x45
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: syscall.Read(...)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/syscall/syscall_unix.go:183
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: internal/poll.ignoringEINTRIO(...)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/internal/poll/fd_unix.go:794
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: internal/poll.(*FD).Read(0xc0000560c0?, {0xc0000fc110?, 0x8?, 0x8?})
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/internal/poll/fd_unix.go:163 +0x285
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: os.(*File).read(...)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/os/file_posix.go:31
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: os.(*File).Read(0xc000014010, {0xc0000fc110?, 0xc0032a84e0?, 0x8?})
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/os/file.go:119 +0x5e
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: io.ReadAtLeast({0x18785a0, 0xc000014010}, {0xc0000fc110, 0x8, 0x8}, 0x8)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/io/io.go:332 +0x9a
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: io.ReadFull(...)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /usr/lib/go/src/io/io.go:351
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: capnproto.org/go/capnp/v3.(*Decoder).Decode(0xc0000fc100)
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /home/opam/go/pkg/mod/capnproto.org/go/capnp/v3@v3.0.0-alpha.5/message.go:632 +0x7d
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]: main.main()
[2023-11-11 01:28:33]  Nov 11 06:28:32 --- mina[1107160]:         /workdir/src/app/libp2p_helper/src/libp2p_helper/main.go:178 +0x811```

**Comment by tizoc** [comment]
@deepthiskumar I reproduced this locally, and what I see is that the genesis ledger rocksdb database is re-created if I kill the node and start it again:

```
> ls -la ./.mina-config/genesis/*
lrwxrwxrwx 1 bruno bruno      119 Nov 14 09:15 ./.mina-config/genesis/genesis_ledger_accounts_3e16f7ed32d2507ceea1f11d6fc1443e82bce2d3b061218501c2c45fe047100f.tar.gz -> /home/bruno/.mina-config/genesis/genesis_ledger_f9147df6bb654a9254e949df54f0ce0f0e8e8f15f694e529377f581ddf91af1a.tar.gz
-rw-rw-r-- 1 bruno bruno 60503673 Nov 14 09:15 ./.mina-config/genesis/genesis_ledger_f9147df6bb654a9254e949df54f0ce0f0e8e8f15f694e529377f581ddf91af1a.tar.gz

./.mina-config/genesis/5a5295d8-cb27-3c37-2cf8-74db5fc2fdee:
total 132880
drwxrwxr-x 2 bruno bruno     4096 Nov 14 09:21 ./
drwxrwxr-x 6 bruno bruno     4096 Nov 14 10:25 ../
-rw-r--r-- 1 bruno bruno 85891843 Nov 14 09:14 000007.sst
-rw-r--r-- 1 bruno bruno 45788545 Nov 14 09:21 000010.sst
-rw-r--r-- 1 bruno bruno        0 Nov 14 09:21 000012.log
-rw-r--r-- 1 bruno bruno       16 Nov 14 09:21 CURRENT
-rw-r--r-- 1 bruno bruno       37 Nov 14 09:13 IDENTITY
-rw-r--r-- 1 bruno bruno        0 Nov 14 09:13 LOCK
-rw-rw-r-- 1 bruno bruno    16948 Nov 14 09:21 LOG
-rw-rw-r-- 1 bruno bruno    18490 Nov 14 09:14 LOG.old.1699964514096580
-rw-r--r-- 1 bruno bruno      227 Nov 14 09:21 MANIFEST-000011
-rw-r--r-- 1 bruno bruno     4771 Nov 14 09:13 OPTIONS-000005
-rw-r--r-- 1 bruno bruno     4784 Nov 14 09:21 OPTIONS-000014

./.mina-config/genesis/7ddde074-4023-3a4a-9bb0-1b42cf3b87ba:
total 132880
drwxrwxr-x 2 bruno bruno     4096 Nov 14 10:25 ./
drwxrwxr-x 6 bruno bruno     4096 Nov 14 10:25 ../
-rw-r--r-- 1 bruno bruno 85891843 Nov 14 09:14 000007.sst
-rw-r--r-- 1 bruno bruno 45788545 Nov 14 10:25 000010.sst
-rw-r--r-- 1 bruno bruno        0 Nov 14 10:25 000012.log
-rw-r--r-- 1 bruno bruno       16 Nov 14 10:25 CURRENT
-rw-r--r-- 1 bruno bruno       37 Nov 14 09:13 IDENTITY
-rw-r--r-- 1 bruno bruno        0 Nov 14 09:13 LOCK
-rw-rw-r-- 1 bruno bruno    16948 Nov 14 10:25 LOG
-rw-rw-r-- 1 bruno bruno    18490 Nov 14 09:14 LOG.old.1699968344825867
-rw-r--r-- 1 bruno bruno      227 Nov 14 10:25 MANIFEST-000011
-rw-r--r-- 1 bruno bruno     4771 Nov 14 09:13 OPTIONS-000005
-rw-r--r-- 1 bruno bruno     4784 Nov 14 10:25 OPTIONS-000014

./.mina-config/genesis/9f241999-ac55-3959-0868-5743d5f4e62b:
total 132880
drwxrwxr-x 2 bruno bruno     4096 Nov 14 10:04 ./
drwxrwxr-x 6 bruno bruno     4096 Nov 14 10:25 ../
-rw-r--r-- 1 bruno bruno 85891843 Nov 14 09:14 000007.sst
-rw-r--r-- 1 bruno bruno 45788545 Nov 14 10:04 000010.sst
-rw-r--r-- 1 bruno bruno        0 Nov 14 10:04 000012.log
-rw-r--r-- 1 bruno bruno       16 Nov 14 10:04 CURRENT
-rw-r--r-- 1 bruno bruno       37 Nov 14 09:13 IDENTITY
-rw-r--r-- 1 bruno bruno        0 Nov 14 09:13 LOCK
-rw-rw-r-- 1 bruno bruno    16948 Nov 14 10:04 LOG
-rw-rw-r-- 1 bruno bruno    18490 Nov 14 09:14 LOG.old.1699967054466789
-rw-r--r-- 1 bruno bruno      227 Nov 14 10:04 MANIFEST-000011
-rw-r--r-- 1 bruno bruno     4771 Nov 14 09:13 OPTIONS-000005
-rw-r--r-- 1 bruno bruno     4784 Nov 14 10:04 OPTIONS-000014

./.mina-config/genesis/f502b3e6-e908-30cc-7dc2-d10d3f371cec:
total 132880
drwxrwxr-x 2 bruno bruno     4096 Nov 14 09:52 ./
drwxrwxr-x 6 bruno bruno     4096 Nov 14 10:25 ../
-rw-r--r-- 1 bruno bruno 85891843 Nov 14 09:14 000007.sst
-rw-r--r-- 1 bruno bruno 45788545 Nov 14 09:52 000010.sst
-rw-r--r-- 1 bruno bruno        0 Nov 14 09:52 000012.log
-rw-r--r-- 1 bruno bruno       16 Nov 14 09:52 CURRENT
-rw-r--r-- 1 bruno bruno       37 Nov 14 09:13 IDENTITY
-rw-r--r-- 1 bruno bruno        0 Nov 14 09:13 LOCK
-rw-rw-r-- 1 bruno bruno    16948 Nov 14 09:52 LOG
-rw-rw-r-- 1 bruno bruno    18490 Nov 14 09:14 LOG.old.1699966324525520
-rw-r--r-- 1 bruno bruno      227 Nov 14 09:52 MANIFEST-000011
-rw-r--r-- 1 bruno bruno     4771 Nov 14 09:13 OPTIONS-000005
-rw-r--r-- 1 bruno bruno     4784 Nov 14 09:52 OPTIONS-000014
```

**Comment by deepthiskumar** [comment]
@tizoc thanks for investigating this! I suspect [this](https://github.com/MinaProtocol/mina/blob/55d20405f195b3f8e4d6603e216798191472d707/src/lib/genesis_ledger_helper/genesis_ledger_helper.ml#L189) is causing it. We could maybe use the same hash used in the tar filename (which should be dependent only on the ledger) and replace it on node startup? Do you have any suggestion?

**Comment by tizoc** [comment]
@deepthiskumar using the hash in the tar filename (which is basically the root hash) is what feels obvious to me, I am just wondering if there is a reason for it to not be the case already. But if that works, then it seems like it would solve the issue (by cleaning up the old directory and re-creating it).

But to me the bigger question is why does the current logic work like it does, and why such intermediary tarball is needed at all (vs just the genesis ledger JSON file and the final genesis ledger directory).
What I see is that inside the `load` function first thing that happens that it tries to [find a tarball to unpack](https://github.com/MinaProtocol/mina/blob/55d20405f195b3f8e4d6603e216798191472d707/src/lib/genesis_ledger_helper/genesis_ledger_helper.ml#L327) (and I see it also searches S3), and if it doesn't exists, then it generates one. But I don't see any attempt to check if the on-disk genesis ledger exists already.

What I would expect instead is for the on-disk genesis ledger to be searched for (and maybe sanity-checked somehow), and reused if it exists. Then if it doesn't then the data from the genesis ledger json file reused to reconstruct it.

**Comment by muratcengiz1** [comment]
Hello All, I'm currently running a node in Mina, and I'm facing an issue with one of my nodes. One node is running smoothly, but the other one is giving me an error stating that the disk is full, as seen in the screenshot below. I reached out for help on Discord, and they suggested cleaning up the disk and restarting, but I haven't received a helpful response from Discord for quite some time.

![image](https://github.com/MinaProtocol/mina/assets/96877933/f4ce111d-e7a5-47c4-a54c-588527ced6d5)

Due to the output shown below, my node is not functioning properly. If I need to follow their advice and clean up the disk before restarting, could you please share the steps with me? I want to make sure I don't make any mistakes. Additionally, if there's an alternative solution, I would appreciate your guidance.

**Comment by deepthiskumar** [comment]
@muratcengiz1 You can just delete the config directory and restart which will trigger a full bootstrap (as there will be no state to bootstrap off of) or you could just delete `.mina-config/genesis/` folder which is taking most of the space. 
I'm curious why you have so many node failures which in turn is causing the disk usage issue. What are some of the errors your node is crashing with?

**Comment by muratcengiz1** [comment]
> @muratcengiz1 You can just delete the config directory and restart which will trigger a full bootstrap (as there will be no state to bootstrap off of) or you could just delete `.mina-config/genesis/` folder which is taking most of the space. I'm curious why you have so many node failures which in turn is causing the disk usage issue. What are some of the errors your node is crashing with?

Hello, How can I delete and restart? Can you share code`s as well? Thanks

**Comment by amc-ie** [comment]
Triage update: Marcin is going to investigate.

**Comment by amc-ie** [comment]
Hi @garethtdavies , this has now been fixed and will be available in the next rampup release which will be landing in the new year. Thank you for taking the time to report this! :)
