### ISSUE TITLE
I am having trouble running the delegation-uptime data sidecar [megathread]

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8230]
Please reply here with any trouble you're having getting the sidecar connected so we can track everything here. Thanks!

---

FAQ

> I get a HTTP error 400 response when my sidecar tries to send data?

Are you running a block producer? This is to collect uptime data from block producers, if you are not running one, the request will fail with this error.

**Comment by Igor-Tselkovskiy** [comment]
I get this error:
root@mina:~# docker run --rm -it -v /etc/mina-sidecar.json:/etc/mina-sidecar.json minaprotocol/mina-bp-stats-sidecar:latest
INFO:root:Found /etc/mina-sidecar.json on the filesystem, using config file
INFO:root:Starting Mina Block Producer Sidecar
ERROR:root:<urlopen error [Errno -2] Name does not resolve>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sidecar.py", line 131, in <module>
    mina_sync_status, head_block_id = fetch_mina_status()
  File "/opt/sidecar.py", line 85, in fetch_mina_status
    response = urllib.request.urlopen(request)
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name does not resolve>
^CTraceback (most recent call last):
  File "/opt/sidecar.py", line 139, in <module>
    time.sleep(5)
