### ISSUE TITLE
Sidecar bug?

### ISSUE THREAD

**Issue by iAmMichaelConnor** [MinaProtocol/mina#8365]
My node's been up since mainnet launch. It ran continuously until yesterday when it crashed for the first time.
I'm running the sidecar as an Ubuntu daemon.
The node is 16 cores 64 GB RAM.

I describe the strange sidecar behaviour below:

Sidecar daemon journalctl logs before crash 1 (all looks good so far):
```
Mar 19 16:59:14 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Got block data
Mar 19 16:59:15 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Finished! New tip 897...
Mar 19 17:02:15 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Fetching block 897...
Mar 19 17:02:17 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Got block data
Mar 19 17:02:17 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Finished! New tip 898...
Mar 19 17:05:17 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Fetching block 898...
```

During crash 1, the error makes sense:

```
Mar 19 17:05:17 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: ERROR:root:<urlopen error [Errno 111] Connection refused>
```
etc...

The crash 1 lasted 18 minutes before the sidecar logs stop throwing errors:

Everything _appeared_ to resume normally...

```
Mar 19 17:23:31 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: ERROR:root:Sleeping for 30s and trying again
Mar 19 17:24:01 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Fetching block 898...
Mar 19 17:24:12 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Got block data
Mar 19 17:24:13 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Finished! New tip 902...
Mar 19 17:27:13 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Fetching block 902...
```

**BUT**

The logs show the sidecar kept logging `block 902` output (every 3 mins) for *4.5 hours*. Before logging `block 903` for *16 hours*.

^^^ That's the first strange set of behaviour. I don't think the node would have taken hours to re-sync after the crash, because this node is so powerful.

**But the story continues...**

After the aforementioned 16 hours of repeated logging of `block 903`, the sidecar threw errors again. And, indeed, the timing of these errors coincide with a _2nd_ time my node crashed. All understandable so far. 

The problem is, that 2nd crash occurred **7 hours ago**, the node appeared to have resynced quickly after the crash, but the sidecar logs show a consistent stream of errors for the past 7 hours. So although the node restarted itself and resynced correctly, the sidecar has broken somehow and spent 7 hours reporting errors instead of reporting my glorious uptime.

Here are the errors:
First this kind of error (repeated every 3 mins):
```
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Fetching block 903...
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: ERROR:root:Response seems to be an error! {"errors":[{"message":"Could not obtain transition frontier","path":["block"]}],"data":null}
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: Traceback (most recent call last):
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 149, in <module>
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:     block_data = fetch_block(current_finalized_tip)
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 107, in fetch_block
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:     raise Exception("Response seems to be an error! {}".format(response_body))
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: Exception: Response seems to be an error! {"errors":[{"message":"Could not obtain transition frontier","path":["block"]}],"data":null}
Mar 20 13:43:40 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: ERROR:root:Sleeping for 30s and trying again
```

Then, after some time, it changed to this similar, but slightly different kind of error:

```
Mar 20 13:47:51 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: INFO:root:Fetching block 903...
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: ERROR:root:Response seems to be an error! {"errors":[{"message":"Could not find block in transition frontier with height 903","path":["block"]}],"data":null}
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: Traceback (most recent call last):
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 149, in <module>
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:     block_data = fetch_block(current_finalized_tip)
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 107, in fetch_block
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]:     raise Exception("Response seems to be an error! {}".format(response_body))
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: Exception: Response seems to be an error! {"errors":[{"message":"Could not find block in transition frontier with height 903","path":["block"]}],"data":null}
Mar 20 13:47:55 Ubuntu-1804-bionic-64-minimal mina-bp-stats-sidecar[17584]: ERROR:root:Sleeping for 30s and trying again
```

^^^ this one repeated for **6.5 hours**, always trying to fetch 903, even though the node had continued keeping up with the blockchain (now on block 1315 which matches the MinaExplorer).

Upon checking my node and realising the errors, I restarted the sidecar daemon manually and it appears to be working again now.

Unfortunately, I'm worried this has possible resulted in many hours of lost "uptime reporting", where my node was synced but the sidecar has been erroring.

**Comment by iAmMichaelConnor** [comment]
In short, it appears there's a bug in the sidecar, that needs a manual restart to make it work again.
I'd prefer not to check my node every day. My beastly node is working beautifully, with lots of continuous uptime. But this possible sidecar bug might be spoiling my chances of earning a sweet, sweet foundation delegation when delegates are reviewed in 60 days. :) 

Please let me know if you'd like any other logs :)

**Comment by iAmMichaelConnor** [comment]
I've done some further digging.

I think the problem came from my node crashing and then being in catchup for ~20 hours (roughly 400 blocks), and so I think I started getting `Could not find block in transition frontier with height 903` errors because my node was further than 290 blocks behind.

Suggested solution for `sidecar.py`:

Because `current_finalized_tip` was last set over 20 hours ago, it is now badly out of date. The `while` loop keeps failing before it can update `current_finalized_tip`, at the line:

`block_data = fetch_block(current_finalized_tip)`, which keeps failing because the `current_finalized_tip` we're querying is no-longer in the frontier.

How to solve this? Add a variable to record the _time_ at which `current_finalized_tip` was last set. If this time was greater than 1 hour ago (for example), then repeat this startup logic, to update `current_finalized_tip` to a valid one.

```
while True:
        try:
            mina_sync_status, head_block_id = fetch_mina_status()
            if mina_sync_status == "SYNCED" or mina_sync_status == "CATCHUP":
                logging.debug("Mina sync status is acceptable ({}), continuing!".format(mina_sync_status))
                break
            logging.info("Mina sync status is {}. Sleeping for 5s and trying again".format(mina_sync_status))
        except Exception as e:
            logging.exception(e)

        time.sleep(5)

    # Go back FINALIZATION_THRESHOLD blocks from the tip to have a finalized block
    current_finalized_tip = head_block_id - FINALIZATION_THRESHOLD
```
(Perhaps wrap this logic into a function of its own, so that it can be called again).

**Comment by iAmMichaelConnor** [comment]
I opened a PR with a suggestion to fix the bug. https://github.com/MinaProtocol/mina/pull/8368. 
(But I've not written python before).

**Comment by Fitblip** [comment]
Hi @iAmMichaelConnor, digging into this further it looks as though the logic should still operate correctly even if the node dies and comes back after a time. 

I suspect your node never got into a proper state since the `fetch_block` call should only error out while the node is unhealthy, but be succeed once things are healthy once again (and then pick up the current tip from the `fetch_block` call)

**Comment by iAmMichaelConnor** [comment]
Mar 19 17:05 - Crashed from 'synced' (and got stuck in 'catchup' until...)
Mar 20 13:45 - Crashed from 'catchup'
Mar 20 14:02 - Synced (and from here it was properly synced continuously; it's been synced ever since)

But from Mar 20 14:02, the sidecar continued reporting the error `"Could not find block in transition frontier with height 903"`

By the time I noticed at Mar 20 20:58, the error was still being reported. I restarted the worker and it started working again, and immediately fetched block 1297.

> I suspect your node never got into a proper state
I think it did get into a proper state (at Mar 20 14:02), and the fact that restarting the sidecar immediately allowed it to fetch 1297 suggests it was in a proper state, and the sidecar hadn't noticed.

That's why I hypothesise that it could be an issue with the sidecar querying a block which is "too old" (block 903), rather than a more recent block.

> any reproduction steps I should take
It was a weird set of circumstances, so can't think of a way to reproduce it. Maybe you could kill a node for 20 hours (whilst keeping the sidecar running), and then restart the node, and see how the sidecar reacts once the node reaches 'synced' again? (Hopefully it continues to throw an error)

**Comment by nicolasochem** [comment]
My sidecar is in this state now.

```
│ ERROR:root:Response seems to be an error! {"errors":[{"message":"Could not find block in transition frontier with height 855","path":["block"]}],"data":null}                                                                                              │
│ Traceback (most recent call last):                                                                                                                                                                                                                         │
│   File "/opt/sidecar.py", line 149, in <module>                                                                                                                                                                                                            │
│     block_data = fetch_block(current_finalized_tip)                                                                                                                                                                                                        │
│   File "/opt/sidecar.py", line 107, in fetch_block                                                                                                                                                                                                         │
│     raise Exception("Response seems to be an error! {}".format(response_body))                                                                                                                                                                             │
│ Exception: Response seems to be an error! {"errors":[{"message":"Could not find block in transition frontier with height 855","path":["block"]}],"data":null}                                                                                              │
│ ERROR:root:Sleeping for 30s and trying again                                                                                                                                                                                                               │
│ INFO:root:Fetching block 855...                                                                                                                                                                                                                            │
│ ERROR:root:Response seems to be an error! {"errors":[{"message":"Could not find block in transition frontier with height 855","path":["block"]}],"data":null}                                                                                              │
│ Traceback (most recent call last):                                                                                                                                                                                                                         │
│   File "/opt/sidecar.py", line 149, in <module>                                                                                                                                                                                                            │
│     block_data = fetch_block(current_finalized_tip)                                                                                                                                                                                                        │
│   File "/opt/sidecar.py", line 107, in fetch_block                                                                                                                                                                                                         │
│     raise Exception("Response seems to be an error! {}".format(response_body))                                                                                                                                                                             │
│ Exception: Response seems to be an error! {"errors":[{"message":"Could not find block in transition frontier with height 855","path":["block"]}],"data":null}                                                                                              │
│ ERROR:root:Sleeping for 30s and trying again                    ```

I also had the block producer crash and restart. Let me know if there is a way I can help debug, otherwise I will restart the sidecar.

**Comment by iAmMichaelConnor** [comment]
@nicolasochem do you have the output from `mina client status`, just as evidence that your node has indeed properly synced?
And (if you've restarted your sidecar by now), did it immediately start working?
That might support my hypothesis that "old block" requests aren't successful, so a newer block needs to be queried (since your sidecar is trying to query block 855 whilst the blockchain is over block 2000 now).
If that's the case, I think my suggested approach in the PR #8368 might solve this.

**Comment by nicolasochem** [comment]
```
root@my-block-producer-979fc76c7-mjwcx:~# mina client status
Using password from environment variable CODA_PRIVKEY_PASS
Mina daemon status
-----------------------------------

Global number of accounts:                     1844
Block height:                                  2955
Max observed block height:                     2955
Max observed unvalidated block height:         2955
Local uptime:                                  6d2h40m1s
Ledger Merkle root:                            jx2dHNhH8CiWziqhZBVyPWcaaB4cGDsu9YdRCva4MoUuC9J7WFh
Protocol state hash:                           3NKoeGngWTqSFKeiFpfm3yQAkzN8Vr81ijqenenmi5Qjgw7Xuqd1
Chain id:                                      5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                                     48401e92d94948c066c03ca76326c065e5cbfc92
Configuration directory:                       /root/.mina-config
Peers:                                         57
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Synced
Catchup status:                                
        To build breadcrumb:           0
        To initial validate:           0
        Finished:                      549
        To verify:                     0
        To download:                   0
        Waiting for parent to finish:  0
```

Yes, I restarted my sidecar and it immediately started working.

```
│                                                                                                                                                                                                                                                            │
│ INFO:root:Found MINA_BP_UPLOAD_URL in the environment, using envar                                                                                                                                                                                         │
│ INFO:root:Found MINA_NODE_URL in the environment, using envar                                                                                                                                                                                              │
│ INFO:root:Starting Mina Block Producer Sidecar                                                                                                                                                                                                             │
│ INFO:root:Fetching block 2944...                                                                                                                                                                                                                           │
│ INFO:root:Got block data                                                                                                                                                                                                                                   │
│ INFO:root:Finished! New tip 2944...                                  
```

I think your analysis is right.

**Comment by nicolasochem** [comment]
@Fitblip did you have a chance to look? It is still happening.

**Comment by Fitblip** [comment]
Hi @nicolasochem, apologies for the delay. We're looking at this internally and trying to reproduce the findings in this bug.

**Comment by Fitblip** [comment]
Hey @nicolasochem / @iAmMichaelConnor this should be fixed! Thanks a ton for the bug report, and apologies for the delay!
