### ISSUE TITLE
Sidecar error: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by timsmith1337** [MinaProtocol/mina#8882]
Sidecar version: **1.1.6-386c5ac**

After updating Sidecar to newest version I am seeing the below error on one of my nodes. This happened 3 times in a span of 1 hour. Please note that, in this case, error initiated after `Fetching block 19738` but afterwards `Found new head at 19752` however continued from block 19740. Block 19739 is skipped.

I haven't seen this error before the newest update and other nodes are unaffected till now (sidecar 1.1.6 & 1.1.5).

```
May 13 16:28:43 mina mina-bp-stats-sidecar[1133]: INFO:root:Fetching block 19738...
May 13 16:28:43 mina mina-bp-stats-sidecar[1133]: INFO:root:Got block data
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: ERROR:root:<urlopen error [Errno -3] Temporary failure in name resolution>
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: Traceback (most recent call last):
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     encode_chunked=req.has_header('Transfer-encoding'))
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 1281, in request
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     self._send_request(method, url, body, headers, encode_chunked)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     self.endheaders(body, encode_chunked=encode_chunked)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     self._send_output(message_body, encode_chunked=encode_chunked)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     self.send(msg)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 980, in send
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     self.connect()
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 1434, in connect
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     super().connect()
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/http/client.py", line 952, in connect
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     (self.host,self.port), self.timeout, self.source_address)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/socket.py", line 704, in create_connection
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: socket.gaierror: [Errno -3] Temporary failure in name resolution
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: During handling of the above exception, another exception occurred:
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: Traceback (most recent call last):
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 159, in <module>
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     send_update(block_data, current_finalized_tip)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 122, in send_update
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     response = urllib.request.urlopen(request)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     return opener.open(url, data, timeout)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 526, in open
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     response = self._open(req, data)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     '_open', req)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     result = func(*args)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     context=self._context, check_hostname=self._check_hostname)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:   File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]:     raise URLError(err)
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
May 13 16:28:53 mina mina-bp-stats-sidecar[1133]: ERROR:root:Sleeping for 30s and trying again
May 13 16:29:23 mina mina-bp-stats-sidecar[1133]: INFO:root:Found new head at 19752
May 13 16:29:23 mina mina-bp-stats-sidecar[1133]: INFO:root:Continuing with finalized tip block of 19740
May 13 16:29:23 mina mina-bp-stats-sidecar[1133]: INFO:root:Fetching block 19740...
May 13 16:29:23 mina mina-bp-stats-sidecar[1133]: INFO:root:Got block data
May 13 16:29:26 mina mina-bp-stats-sidecar[1133]: INFO:root:Finished! New tip 19740...
May 13 16:32:26 mina mina-bp-stats-sidecar[1133]: INFO:root:Fetching block 19740...
May 13 16:32:26 mina mina-bp-stats-sidecar[1133]: INFO:root:Got block data
May 13 16:32:29 mina mina-bp-stats-sidecar[1133]: INFO:root:Finished! New tip 19740...
May 13 16:35:29 mina mina-bp-stats-sidecar[1133]: INFO:root:Fetching block 19740...
May 13 16:35:39 mina mina-bp-stats-sidecar[1133]: INFO:root:Got block data
May 13 16:35:41 mina mina-bp-stats-sidecar[1133]: INFO:root:Finished! New tip 19741...
May 13 16:38:41 mina mina-bp-stats-sidecar[1133]: INFO:root:Fetching block 19741...
May 13 16:38:41 mina mina-bp-stats-sidecar[1133]: INFO:root:Got block data
May 13 16:38:42 mina mina-bp-stats-sidecar[1133]: INFO:root:Finished! New tip 19742...
```

Firewall setting: SSH & 8302/tcp only. Private IPs are blocked.

**Comment by timsmith1337** [comment]
Closing this as I understand there was `network config` issue from my end.
