### ISSUE TITLE
sidecar does not throw error when it cannot send data successfully

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#8885]
Sidecar skipped reporting block 19362. Perhaps a timing issue where the node hadn't quite seen 19362 when it was polled, but got it and 19363 before the next poll?

May 12 10:20:14 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
May 12 10:20:14 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 19363...
May 12 10:17:14 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 19363...
May 12 10:15:03 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
May 12 10:15:03 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 19361...
May 12 10:12:03 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 19361...
May 12 10:09:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
May 12 10:09:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 19360...
May 12 10:06:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 19360...

Separately, sidecar got an HTTP Error 408 returned on the next poll after reporting 19363. I think it was just a random one-off node timeout, but listing in case relevant. 

May 12 10:31:18 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 19365...
May 12 10:29:07 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
May 12 10:29:07 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 19364...
May 12 10:26:07 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 19364...
May 12 10:23:56 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
May 12 10:23:56 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 19363...
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]: ERROR:root:Sleeping for 30s and trying again
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]: urllib.error.HTTPError: HTTP Error 408: Request Timeout
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     result = func(*args)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     return self._call_chain(*args)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 561, in error
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     response = self.parent.error(
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     response = meth(req, response)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 523, in open
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     return opener.open(url, data, timeout)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     response = urllib.request.urlopen(request)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 122, in send_update
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:     send_update(block_data, current_finalized_tip)
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 153, in <module>
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]: Traceback (most recent call last):
May 12 10:23:26 mina-mainnet-vt-1 python3[35040]: ERROR:root:HTTP Error 408: Request Timeout

The node in question was in sync from May 10 22:05:04 through May 13 09:38:59; the HTTP 408 above was the only error reported in sidecar logs during that interval.

**Comment by jrwashburn** [comment]
I think this is caused by an IPV6 firewall configuration issue on my end. This communication was going ipv6 and was being blocked. I don't know why it was not throwing a comms error - instead, it usually looks like it succeeded but took two minutes ... I believe it was never getting through at all. I fixed the FW config and now am back to no delay between those two log messages / sending (I assume) successfully!

It should throw an error. (That 408 is very rare -- normally, it just looked like with the 2+ minute delay but no error as above:
May 12 10:12:03 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 19361...
May 12 10:09:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data

**Comment by jrwashburn** [comment]
And even post firewall change, I still see symptoms of very slow send without any error:

May 20 21:23:08 mina-mainnet-vt-1 python3[56521]: INFO:root:Finished! New tip 22280...
May 20 21:20:57 mina-mainnet-vt-1 python3[56521]: INFO:root:Got block data
May 20 21:20:55 mina-mainnet-vt-1 python3[56521]: INFO:root:Fetching block 22279...

**Comment by jrwashburn** [comment]
Closing; new uptime system so this will be irrelevant.
